version: "3"
services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper


  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/
    depends_on:
      - kafka
    hostname: mongo
    environment:
      MONGODB_DATA_DIR: /data/db

  mongo_executor:
    container_name: mongo_executor:1.0
    image: sfereres/mongo:mongo_executor
    depends_on:
      - mongo
    
  web:
    container_name: web
    image: alejandrorg7/web
    ports:
      - "5000:5000"
      - "9200:9200"
    depends_on:
      - mongo_executor
      - spark
    hostname: web
    environment:
      MONGO_URI: mongo
      KAFKA_URI: kafka
      FLASK_URI: web

  spark:
    image: sfereres/spark:1.2
    container_name: spark:1.2
    ports:
      - "7077:7077"
    depends_on:
      - kafka
      - mongo_executor
    hostname: spark
    environment:
      MONGO_URI: mongo
      KAFKA_URI: kafka


volumes:
  data:
